name: Build Release

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    name: Build Linux Amd64
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
        
    - name: Build binary
      run: |
        # 确保build.sh可执行
        chmod +x build.sh
        # 运行构建脚本
        ./build.sh
        
    - name: Check binary
      run: |
        if [ ! -f "telegram-bot-template" ]; then
          echo "Binary not found!"
          exit 1
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: telegram-bot-template
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        