name: Build Release

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    name: Build Linux Amd64
    runs-on: ubuntu-latest
    container: debian:12
    
    steps:
    - name: Install system dependencies
      run: |
        echo "=== 构建环境信息 ==="
        cat /etc/os-release
        echo "Python版本: $(python3 --version)"
        echo "Curl版本: $(curl --version | head -1)"
        echo "==================="
        apt-get update
        apt-get install -y curl wget git python3 python3-pip python3-venv
    
    - uses: actions/checkout@v4
    
    - name: Set up Python environment
      run: |
        python3 -m venv venv
        . venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
        
    - name: Build binary
      run: |
        . venv/bin/activate
        # 确保build.sh可执行
        chmod +x build.sh
        # 运行构建脚本
        ./build.sh
        
    - name: Check binary
      run: |
        if [ ! -f "telegram-bot-template" ]; then
          echo "Binary not found!"
          exit 1
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: telegram-bot-template
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
